name: PR Verifier

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Adjust if you're using a different Node version

      - name: Install dependencies
        run: npm i

      - name: Build (Vite)
        run: npm run build
